// Canceled orders notification email template

import { getStoreInfo } from "../store-info";
import { CanceledOrdersEmailData } from "../types";

export function generateCanceledOrdersEmail(data: CanceledOrdersEmailData): {
	html: string;
	text: string;
} {
	const { canceledOrders, totalAmount, date } = data;
	const store = getStoreInfo();

	const formattedDate = new Date(date).toLocaleString("en-NG", {
		dateStyle: "full",
	});

	const formatCurrency = (amount: number) =>
		`₦${amount.toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

	const ordersHtml = canceledOrders
		.map(
			(order) => `
    <tr>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; color: #374151;">${order.id}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; color: #374151;">${order.customerName || "Walk-in Customer"}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: right; color: #374151;">${formatCurrency(order.total)}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; color: #6b7280; font-size: 13px;">${new Date(order.createdAt).toLocaleString("en-NG", { dateStyle: "short", timeStyle: "short" })}</td>
    </tr>
  `,
		)
		.join("");

	const ordersText = canceledOrders
		.map(
			(order) =>
				`${order.id} | ${order.customerName || "Walk-in"} | ${formatCurrency(order.total)} | ${new Date(order.createdAt).toLocaleString("en-NG", { dateStyle: "short", timeStyle: "short" })}`,
		)
		.join("\n");

	const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Canceled Orders Report</title>
      </head>
      <body style="margin: 0; padding: 0; font-family: Arial, sans-serif; background-color: #f3f4f6;">
        <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f3f4f6; padding: 20px;">
          <tr>
            <td align="center">
              <table width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
                <!-- Header -->
                <tr>
                  <td style="background-color: #dc2626; padding: 30px; text-align: center;">
                    <h1 style="margin: 0 0 10px; color: #ffffff; font-size: 24px;">Automated Order Cancellation Report</h1>
                    <p style="margin: 0; color: #fecaca; font-size: 14px;">${formattedDate}</p>
                  </td>
                </tr>
                
                <!-- Summary -->
                <tr>
                  <td style="padding: 30px 30px 20px;">
                    <div style="background-color: #fef2f2; border: 1px solid #fecaca; border-radius: 6px; padding: 20px;">
                      <p style="margin: 0 0 10px; font-size: 16px; color: #991b1b;">
                        <strong>Summary:</strong> ${canceledOrders.length} pending order(s) were automatically canceled at midnight.
                      </p>
                      <p style="margin: 0; font-size: 18px; color: #991b1b;">
                        <strong>Total Amount:</strong> ${formatCurrency(totalAmount)}
                      </p>
                    </div>
                  </td>
                </tr>
                
                <!-- Orders Table -->
                <tr>
                  <td style="padding: 0 30px 30px;">
                    <h2 style="margin: 0 0 15px; font-size: 18px; color: #111827;">Canceled Orders</h2>
                    <table width="100%" cellpadding="0" cellspacing="0" style="border: 1px solid #e5e7eb; border-radius: 6px; overflow: hidden;">
                      <tr style="background-color: #f9fafb;">
                        <td style="padding: 12px; font-weight: bold; color: #111827; border-bottom: 2px solid #e5e7eb;">Order ID</td>
                        <td style="padding: 12px; font-weight: bold; color: #111827; border-bottom: 2px solid #e5e7eb;">Customer</td>
                        <td style="padding: 12px; font-weight: bold; color: #111827; text-align: right; border-bottom: 2px solid #e5e7eb;">Amount</td>
                        <td style="padding: 12px; font-weight: bold; color: #111827; border-bottom: 2px solid #e5e7eb;">Created</td>
                      </tr>
                      ${ordersHtml}
                    </table>
                  </td>
                </tr>
                
                <!-- Footer -->
                <tr>
                  <td style="background-color: #f9fafb; padding: 20px 30px; border-top: 1px solid #e5e7eb;">
                    <p style="margin: 0 0 10px; font-size: 14px; color: #374151;">
                      This is an automated report generated by ${store.name}'s scheduled task.
                    </p>
                    <p style="margin: 0 0 10px; font-size: 12px; color: #9ca3af;">
                      All pending orders are automatically canceled at midnight to maintain data integrity.
                    </p>
                    <div style="margin-top: 15px; padding-top: 15px; border-top: 1px solid #e5e7eb; text-align: center;">
                      <p style="margin: 5px 0; font-size: 12px; color: #6b7280;"><strong>${store.name}</strong></p>
                      ${store.address ? `<p style="margin: 5px 0; font-size: 12px; color: #6b7280;">${store.address}</p>` : ""}
                      ${store.phone ? `<p style="margin: 5px 0; font-size: 12px; color: #6b7280;">Phone: ${store.phone}</p>` : ""}
                      ${store.email ? `<p style="margin: 5px 0; font-size: 12px; color: #6b7280;">Email: ${store.email}</p>` : ""}
                    </div>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </body>
    </html>
  `;

	const text = `
AUTOMATED ORDER CANCELLATION REPORT
${formattedDate}

SUMMARY:
${canceledOrders.length} pending order(s) were automatically canceled at midnight.
Total Amount: ${formatCurrency(totalAmount)}

CANCELED ORDERS:
Order ID | Customer | Amount | Created
${ordersText}

---
This is an automated report generated by ${store.name}'s scheduled task.
All pending orders are automatically canceled at midnight to maintain data integrity.

${store.name}
${store.address || ""}
${store.phone ? `Phone: ${store.phone}` : ""}
${store.email ? `Email: ${store.email}` : ""}
  `.trim();

	return { html, text };
}
